### ISSUE TITLE
errors when trying to compile

### ISSUE THREAD

**Issue by Artim96** [null4n/ffmpeg-android-maker#1]
I've retried your fork now to write down the errors. First I tried using the Docker Image from Javernaut with
`docker run --rm -v /opt/ffmpeg-android-maker/:/mnt/ffmpeg-android-maker -e FAM_ARGS="--target-abis=arm64 --android-api-level=33 --enable-libaom --enable-libdav1d --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libspeex --enable-libvpx --enable-libwebp --enable-libx264 --enable-libfdk-aac" javernaut/ffmpeg-android-maker`

It did compile for a while but then ended with
```
INSTALL libavutil/replaygain.h
INSTALL libavutil/ripemd.h
INSTALL libavutil/samplefmt.h
INSTALL libavutil/sha.h
INSTALL libavutil/sha512.h
INSTALL libavutil/spherical.h
INSTALL libavutil/stereo3d.h
INSTALL libavutil/threadmessage.h
INSTALL libavutil/time.h
INSTALL libavutil/timecode.h
INSTALL libavutil/timestamp.h
INSTALL libavutil/tree.h
INSTALL libavutil/twofish.h
INSTALL libavutil/uuid.h
INSTALL libavutil/version.h
INSTALL libavutil/video_enc_params.h
INSTALL libavutil/xtea.h
INSTALL libavutil/tea.h
INSTALL libavutil/tx.h
INSTALL libavutil/film_grain_params.h
INSTALL libavutil/avconfig.h
INSTALL libavutil/ffversion.h
INSTALL libavutil/libavutil.pc
/root/android-sdk/ndk/25.0.8775105/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-readelf: error: '/mnt/ffmpeg-android-maker/build/ffmpeg/arm64-v8a/lib/*.so': No such file or directory
cp: cannot stat '/mnt/ffmpeg-android-maker/build/ffmpeg/arm64-v8a/lib/*.so': No such file or directory
```

I then tried to build the docker image myself, but it failed the same way Javernauts did so we probably have to wait until it's updated
`docker build /opt/ffmpeg-android-maker/tools/docker/`
```
=> CACHED [5/6] RUN mkdir -p /root/android-sdk &&   unzip -qq /root/android-sdk.zip -d /root/android-sdk &&   rm /root/android-sdk.zip        0.0s
 => ERROR [6/6] RUN installAndroidComponent() { yes | /root/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=/root/android-sdk "$1" > /dev  0.4s
------
 > [6/6] RUN installAndroidComponent() { yes | /root/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=/root/android-sdk "$1" > /dev/null; } &&   installAndroidComponent "ndk;25.2.9519653" &&   installAndroidComponent "cmake;3.22.1":
#0 0.412 Error: A JNI error has occurred, please check your installation and try again
#0 0.412 Exception in thread "main" java.lang.UnsupportedClassVersionError: com/android/prefs/AndroidLocationsProvider has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
#0 0.412        at java.lang.ClassLoader.defineClass1(Native Method)
#0 0.412        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
#0 0.412        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
#0 0.412        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
#0 0.412        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
#0 0.412        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
#0 0.412        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
#0 0.412        at java.security.AccessController.doPrivileged(Native Method)
#0 0.413        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
#0 0.413        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
#0 0.413        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
#0 0.413        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
#0 0.413        at java.lang.Class.getDeclaredMethods0(Native Method)
#0 0.413        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
#0 0.413        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
#0 0.413        at java.lang.Class.getMethod0(Class.java:3018)
#0 0.413        at java.lang.Class.getMethod(Class.java:1784)
#0 0.413        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:650)
#0 0.413        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:632)
------
Dockerfile:50
--------------------
  49 |     # Installing components through the Android SDK
  50 | >>> RUN installAndroidComponent() { yes | ${ANDROID_SDK_HOME}/cmdline-tools/bin/sdkmanager --sdk_root=${ANDROID_SDK_HOME} "$1" > /dev/null; } && \
  51 | >>>   installAndroidComponent "ndk;${VERSION_NDK}" && \
  52 | >>>   installAndroidComponent "cmake;${VERSION_CMAKE}"
  53 |
--------------------
ERROR: failed to solve: process "/bin/sh -c installAndroidComponent() { yes | ${ANDROID_SDK_HOME}/cmdline-tools/bin/sdkmanager --sdk_root=${ANDROID_SDK_HOME} \"$1\" > /dev/null; } &&   installAndroidComponent \"ndk;${VERSION_NDK}\" &&   installAndroidComponent \"cmake;${VERSION_CMAKE}\"" did not complete successfully: exit code: 1
```

Working without Docker, setting up SDK, NDK and cmake like written in the Dockerfile on Pop 22.04 resulted the exact same error as trying to compile it in Javernauts Docker image.

**Comment by null4n** [comment]
the first docker build is success, because we disable shared, so it dont compile shared library .so files. copy build/$ABI/bin/ffmpeg to somewhere then run it

**Comment by null4n** [comment]
OK, I found the code cause this. It check text relocation for .so library files which static binary dont need. I have disabled it

**Comment by Artim96** [comment]
Yes, it's working, the error message was just confusing. Now I just have to see what the proper command for hardware accelerated transcoding looks like. And test it against software transcoding.

**Comment by null4n** [comment]
ffmpeg -hwaccels
ffmpeg -codecs|grep mediacodec

atm only h264 and hevc have mediacodec encoder which support hardware accelerated

**Comment by Artim96** [comment]
I know, question was just if it was as simple as a find & replace of a command that uses like QSV or more complicated.

But at least VP9 and AV1 decoding are already supported in hardware.

Quick test transcoding a simple 720p24 11:30 min video from h264 to h265 (simply copying the audio): 1:39. Sadly no way to test that against software transcoding as h265 is only supported for hwaccel usage and for v4l2 usage. So I had to do either h264 to h264 or h265 to h265. But it still sounds to me like this is decently fast.

I simply had to copy ffmpeg to Termux' home folder (~/), add execute permissions and run
`./ffmpeg_hwacc -v error -hwaccel mediacodec -c:v h264_mediacodec -i /sdcard/input.mp4 -c:v h265_mediacodec -b:v 900k -c:a copy /sdcard/output_h265.mp4`

**Comment by null4n** [comment]
I try to add libx265 in this build, but ffmpeg configure failed. I didnt find how to fix

**Comment by Artim96** [comment]
Probably for a reason. I also have a simple app that can do this, but it's still based on FFMPEG 4, it also doesn't include it. Maybe interest in that is just too low to bother fixing.

**Comment by null4n** [comment]
I finally add libx265 for arm64-v8a build.

**Comment by Artim96** [comment]
Nice, thanks. I'll do a comparison soon.

**Comment by Artim96** [comment]
> CANNOT LINK EXECUTABLE "./ffmpeg": library "libx265.so.188" not found: needed by main executable

Seems something's still not finished.

PS: you might also want to add `--enable-small` to the ffmpeg build script. It reduced size by 17 % for me.
